import { Inter } from 'next/font/google';
import { Providers } from './providers';
import Nav from './components/Nav/Nav';
import './globals.css';
import getAuthTokenName from './helpers/getAuthTokenName';
import { cookies } from 'next/headers';
import styles from './layout.module.css';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Stellar',
  description: 'Generated by juanito bebote',
};

export default function RootLayout({ children }) {
  const nextCookies = cookies();
  const nextAuthSessionToken = nextCookies.get(getAuthTokenName());

  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.layout}`}>
        <Providers>
          <Nav token={nextAuthSessionToken?.value} />
          <div className={styles.pageContent}>{children}</div>
          <footer className={styles.footer}>dev: juanchaher99@gmail.com</footer>
        </Providers>
      </body>
    </html>
  );
}
