import { Inter } from 'next/font/google';
import Nav from './components/Nav/Nav';
import styles from './layout.module.css';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Stellar',
  description: 'Generated by juanito bebote',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.layout}`}>
        <Nav />
        <div className={styles.pageContent}>{children}</div>
      </body>
    </html>
  );
}
